site_name: Architecture Decision Records
theme:
  name: material

plugins:
  - search
  - macros
  - mermaid2
  - awesome-pages
  - literate-nav

nav:
  - Overview: index.md
  - "adr/*.md"

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
