site_name: Architecture Decision Records
theme:
  name: material

plugins:
  - search
  - macros
  - mermaid2
  - awesome-pages

nav:
  - Overview: index.md
  - ... | glob: adr/*.md

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
